name: Sync File to Another Repository

on:
  push:
    paths:
      - "tokens/starc.json"
      - "tokens/vuddy.json"
jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
      - name: Set Current timestamp
        id: timestamp
        run: |
          TIMESTAMP=$(TZ='Asia/Seoul' date +"%Y-%m-%d")
          echo "TIMESTAMP=${TIMESTAMP}" >> $GITHUB_ENV

      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: levvels-design-tokens
          ref: main

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: tf-dive/starc-admin-fe
          token: ${{ secrets.PAT }}
          path: starc-admin-fe
          ref: develop

      - name: Get changed file path
        id: get_changed_file
        run: |
          CHANGED_FILE=$(git --no-pager diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '.json') >> $GITHUB_ENV
          echo "CHANGED_FILE=${CHANGED_FILE}" >> $GITHUB_ENV

      - name: Copy file to target repository
        run: |
          cp levvels-design-tokens/${{ env.GITHUB_ENV }} starc-admin-fe/
          cd starc-admin-fe
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b feature/design-token-update-${{ env.TIMESTAMP }}
          git add .
          git commit -m "Sync file.txt from source repository"
          git push origin feature/design-token-update-${{ env.TIMESTAMP }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: Sync file.txt from source repository
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          title: Sync token file from source repository
          body: This PR syncs token file from source repository
          labels: auto-merge
