name: Sync File to Another Repository

on:
  workflow_run:
    workflows: [Transform]
    types:
      - completed
  workflow_dispatch:
    inputs:
      target:
        type: choice
        options:
          - starc
          - vuddy
        default: ""

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
      - name: Set Current timestamp
        id: timestamp
        run: |
          TIMESTAMP=$(TZ='Asia/Seoul' date +"%Y-%m-%d-%H%M")
          echo "TIMESTAMP=${TIMESTAMP}" >> $GITHUB_ENV

      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: levvels-design-tokens
          ref: main
          fetch-depth: 2

      - name: Set target repo from dispatch inputs
        if: github.event.inputs.target != ''
        run: |
          if [[ "${{ github.event.inputs.target }}" == "starc" ]]; then echo "TARGET_REPO=starc-admin-fe" >> $GITHUB_ENV; else echo "TARGET_REPO=vuddy-fe" >> $GITHUB_ENV; fi
          if [[ "${{ github.event.inputs.target }}" == "starc" ]]; then echo "CHANGED_FILE=token/starc.json" >> $GITHUB_ENV; else echo "CHANGED_FILE=token/vuddy.json" >> $GITHUB_ENV; fi

      - name: Get previous commit SHA
        id: previous_commit
        if: github.event.inputs.target == ''
        run: |
          cd levvels-design-tokens
          echo "PREVIOUS_SHA=$(git rev-parse HEAD~1)" >> $GITHUB_ENV
          cd ..

      - name: Get changed file path
        id: get_changed_file
        if: github.event.inputs.target == ''
        run: |
          cd levvels-design-tokens
          git fetch origin ${{ env.PREVIOUS_SHA }}
          echo "$(git --no-pager diff --name-only ${{ env.PREVIOUS_SHA }} ${{ github.sha }} | grep '.json')"
          CHANGED_FILE=$(git --no-pager diff --name-only ${{ env.PREVIOUS_SHA }} ${{ github.sha }} | grep '.json')
          echo "CHANGED_FILE=${CHANGED_FILE}" >> $GITHUB_ENV
          if [[ ${CHANGED_FILE} == *starc* ]]; then echo "TARGET_REPO=starc-admin-fe" >> $GITHUB_ENV; else echo "TARGET_REPO=vuddy-fe" >> $GITHUB_ENV; fi
          cd ..

      - name: Transform Token Json To Typescript
        run: |
          cd levvels-design-tokens
          echo "npm run transform:fe ${CHANGED_FILE}"
          cat fe/vuddyDesignToken.ts
          if [[ ${TARGET_REPO} == *starc* ]]; then echo "TRANSFORM_FILE=fe/starcDesignToken.ts" >> $GITHUB_ENV; else echo "TRANSFORM_FILE=fe/vuddyDesignToken.ts" >> $GITHUB_ENV; fi
          cd ..

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: tf-dive/${{ env.TARGET_REPO }}
          token: ${{ secrets.PAT }}
          path: ${{ env.TARGET_REPO }}
          ref: develop

      - name: Copy file to target repository
        run: |
          BRANCH_NAME="feature/design-token-update-${{ env.TIMESTAMP }}"

          cp -rvf levvels-design-tokens/${{ env.TRANSFORM_FILE }} ${{ env.TARGET_REPO }}/packages/vuddy-shared/src/
          cd ${{ env.TARGET_REPO }}
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "Sync file.txt from source repository"
          git push origin $BRANCH_NAME

          echo "${{ secrets.PAT }}" > token

          gh auth login --with-token < token
          gh pr create \
            --body "" \
            --title "chore: update design token" \
            --head "$BRANCH_NAME" \
            --base "develop"
